### ISSUE TITLE
FR: Button to delete text in center pane if it's deleted on one side

### ISSUE THREAD

**Issue by ilyagr** [BearToCode/mismerge#16]
Let's say I'm in this state:

![image](https://github.com/BearToCode/mismerge/assets/4123047/20ae02c4-3ee0-4371-81d4-624f9deeacc5)

There is a nice button that allows me to move the insertion of `a` from the right pane the middle pane.

I'd like there to also be a nice button to move the deletion of `c` from the left pane to the middle pane.

P.S. I might file a few more FRs shortly. This is probably the most important of them, though.

I'm currently trying to make a diff editor with the ancient https://codemirror.net/5/demo/merge.html. `mismerge` is the best alternative to it I found, and I thought I'd record my wishlist for it. Thanks for making it! It's a pretty UI.

**Comment by BearToCode** [comment]
Hi @ilyagr ,
I'm glad you like the editor! 
I'll try to add the features you requested, as they seem pretty simple to implement. I'd also like to rewrite some parts of the editor to make it more easy for other people to contribute.

**Comment by ilyagr** [comment]
It works. Very nice :)
