### ISSUE TITLE
[Bug] React adapter throws "TypeError: Super expression must either be null or a function" 

### ISSUE THREAD

**Issue by Haffelchen** [BearToCode/mismerge#24]
I use Nextjs v14 with TypeScript. I've installed both the `@mismerge/core` and the `@mismerge/react` packages
Whenever I try to use the MisMerge editor (both 2 and 3), I get a "TypeError: Super expression must either be null or a function". Interstingely, the editor, near as I can tell, seems to work without any issues. But due to this error I cannot build my app

Code that I use:
```
import '@mismerge/core/dark.css';
import '@mismerge/core/styles.css';

import { useState } from 'react';

import { DefaultDarkColors, MisMerge3 } from '@mismerge/react';

interface MergeEditorProps {
  oldValue?: string;
  newValue?: string;
  onSubmit: (value: string) => Promise<void>;
  onCancel: () => void;
}

export default function MergeEditor({
  oldValue = '',
  newValue = '',
  onSubmit,
  onCancel,
}: MergeEditorProps) {
  const [custom, setCustom] = useState(oldValue ?? '');

  return (
    <div
      style={{
        width: '100%',
        minWidth: '1000px',
        display: 'flex',
        flexDirection: 'column',
      }}
    >
      <MisMerge3
        lhs={oldValue}
        ctr={custom}
        rhs={newValue}
        onCtrChange={setCustom}
        colors={DefaultDarkColors}
        wrapLines={true}
      />

      <button onClick={() => onSubmit(custom)}>Submit</button>
      <button onClick={onCancel}>Cancel</button>
    </div>
  );
};
```

I tried to track down the root cause, but wasn't able to find anything that would indicate what exactly is leading to this issue. Other dependencies seem to be all up 
/to date
I will see if I get the same issue in different environments and with fresh Nextjs apps too, because I really really badly want to use this merge editor! :D

**Comment by Haffelchen** [comment]
Setup a fresh NextJS app and tried again. Same issue, however this time I got some more details in the actual paths that might help:
```
TypeError: Super expression must either be null or a function
    at d (file:///home/haffel/Desktop/TEMP/mismerge-test/node_modules/.pnpm/@mismerge+core@1.2.0_svelte@4.2.18/node_modules/@mismerge/core/dist/web.js:1:9994)
    at file:///home/haffel/Desktop/TEMP/mismerge-test/node_modules/.pnpm/@mismerge+core@1.2.0_svelte@4.2.18/node_modules/@mismerge/core/dist/web.js:1:19427
    at Mt (file:///home/haffel/Desktop/TEMP/mismerge-test/node_modules/.pnpm/@mismerge+core@1.2.0_svelte@4.2.18/node_modules/@mismerge/core/dist/web.js:1:19574)
    at file:///home/haffel/Desktop/TEMP/mismerge-test/node_modules/.pnpm/@mismerge+core@1.2.0_svelte@4.2.18/node_modules/@mismerge/core/dist/web.js:1:33511
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
```

**Comment by Haffelchen** [comment]
More testing later it turns out to be some sort of issue with either Nextjs, or my particular setup. Both the Vite Demo pages of the msimerge repo, as well as a fresh Vite page worked flawless

**Comment by BearToCode** [comment]
Hi, this was due to how the core bundled was imported. I moved it to a dynamic import and now it works fine. Remember to use `'use client'` on top of your component.

**Comment by Haffelchen** [comment]
Works now. Thank you very much!
